# fly.toml app configuration file generated for xevi on 2023-07-04T19:24:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xevi"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = [54321, 443]
  auto_rollback = true

[env]
  PORT= 54321

[[services]]
  http_checks = []
  processes = ["app"]
  internal_port = 54321
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    handlers = ["tls"]
    port = "54321"
    tls_options = { "alpn" = ["h2"] }

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"