name: Rust application ephemeral environment build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Check Protoc
      run: protoc --version

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.2
      
    - name: run bcp
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target x86_64-unknown-linux-musl --release